<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');


$config= array(
    'buyers_post' =>array(
        array('field'=>'barcode','label'=>'Barcode','rules'=>'trim',),
        array('field'=>'co_name','label'=>'Company Name','rules'=>'trim',),
        array('field'=>'description','label'=>'Description','rules'=>'trim',),
        array('field'=>'cont_per_fn','label'=>'Contact First Name','rules'=>'trim|max_length[50]',),
        array('field'=>'cont_per_ln','label'=>'Contact Last Name','rules'=>'trim|max_length[50]',),
        array('field'=>'mi','label'=>'Middle Initial','rules'=>'trim',),
        array('field'=>'title','label'=>'Title','rules'=>'trim',),     
        array('field'=>'salutation','label'=>'Salutation','rules'=>'trim',),
        array('field'=>'gender','label'=>'Gender','rules'=>'trim|max_length[50]',),
        array('field'=>'age_group','label'=>'Age Group','rules'=>'trim',),
        array('field'=>'birthdate','label'=>'Date of Birth','rules'=>'trim',),
        array('field'=>'nationality','label'=>'Nationality','rules'=>'trim',),
        array('field'=>'accompanying_person','label'=>'Accompanying person','rules'=>'trim',),
        array('field'=>'country','label'=>'Country','rules'=>'trim',),
        array('field'=>'continent','label'=>'Continent','rules'=>'trim',),
        array('field'=>'states','label'=>'States','rules'=>'trim',),
        array('field'=>'region','label'=>'Region','rules'=>'trim',),
        array('field'=>'area','label'=>'Area','rules'=>'trim|max_length[32]',),
        array('field'=>'province','label'=>'Province','rules'=>'trim',),
        array('field'=>'add_st','label'=>'Street Address','rules'=>'trim|max_length[50]',),
        array('field'=>'add_city','label'=>'City Address','rules'=>'trim|max_length[50]',),
        array('field'=>'zipcode','label'=>'Zipcode','rules'=>'trim|max_length[5]',),
        array('field'=>'tel_off','label'=>'Office telephone','rules'=>'trim',),
        array('field'=>'tel_show','label'=>'Showroom Telephone','rules'=>'trim',),
        array('field'=>'fax','label'=>'Fax number','rules'=>'trim',),
        array('field'=>'email','label'=>'Email','rules'=>'trim|required|valid_email',),
        array('field'=>'email2','label'=>'Second email','rules'=>'trim',),
        array('field'=>'work_email','label'=>'Work email','rules'=>'trim',),
        array('field'=>'webpage','label'=>'Webpage','rules'=>'trim',),
        array('field'=>'first_time_asia','label'=>'First time asia','rules'=>'trim',),
        array('field'=>'attend_mfi','label'=>'Attend MFI','rules'=>'trim',),
        array('field'=>'pref_day','label'=>'Pref Day','rules'=>'trim',),
        array('field'=>'venue','label'=>'Venue','rules'=>'trim',),
        array('field'=>'deleted','label'=>'Deleted','rules'=>'trim',),
        array('field'=>'mobile','label'=>'Mobile','rules'=>'trim',),
        array('field'=>'exhi_conf_gov','label'=>'exhi_conf_gov','rules'=>'trim',),
        array('field'=>'added','label'=>'Added','rules'=>'trim',),
        array('field'=>'added_value','label'=>'Added Value','rules'=>'trim',),
        array('field'=>'added_count','label'=>'Added Count','rules'=>'trim',),
        array('field'=>'unsubscribe','label'=>'Unsubscribe','rules'=>'trim',),
        array('field'=>'marked','label'=>'marked','rules'=>'trim',),
        array('field'=>'tag','label'=>'Tag','rules'=>'trim',),
        array('field'=>'gcclaimed','label'=>'GC Claimed','rules'=>'trim',),
        array('field'=>'gcdate','label'=>'GC Date','rules'=>'trim',),
        array('field'=>'pid','label'=>'PID','rules'=>'trim',),
        array('field'=>'cutoff','label'=>'Cutoff','rules'=>'trim',),
        // array('field'=>'remarks','label'=>'remarks','rules'=>'trim',),
        array('field'=>'specific_request','label'=>'Specific request','rules'=>'trim',),
        array('field'=>'number_retail_stores','label'=>'Number of retail Store','rules'=>'trim',),
        array('field'=>'list_of_clients','label'=>'List of Clients','rules'=>'trim',),
        array('field'=>'facebook','label'=>'Facebook','rules'=>'trim',),
        array('field'=>'linkedin','label'=>'Linkedin','rules'=>'trim',),
        array('field'=>'blogsite','label'=>'Blog Site','rules'=>'trim',),
        array('field'=>'twitter','label'=>'Twitter','rules'=>'trim',),
        array('field'=>'instagram','label'=>'Instagram','rules'=>'trim',),
        array('field'=>'pinterest','label'=>'Pinterest','rules'=>'trim',),
        array('field'=>'weibo','label'=>'Weibo','rules'=>'trim',),
        array('field'=>'social_others','label'=>'Other Social Media Accounts','rules'=>'trim',),
        array('field'=>'y_estab','label'=>'Year Established','rules'=>'trim',),
        array('field'=>'rfid','label'=>'RFID','rules'=>'trim',),
        array('field'=>'org_name','label'=>'Organization Name','rules'=>'trim',),
        array('field'=>'org_website','label'=>'Organization Website','rules'=>'trim',),
        // array('field'=>'fameplus_id','label'=>'FAME+ ID','rules'=>'trim',),
        array('field'=>'password','label'=>'Password','rules'=>'trim',),

        array('field'=>'fair_code','label'=>'Fair Code','rules'=>'trim',),
        array('field'=>'sector','label'=>'Sector','rules'=>'trim',),
        array('field'=>'remarks','label'=>'Remarks','rules'=>'trim',),
        array('field'=>'pre_reg','label'=>'Pre Reg','rules'=>'trim',),
        array('field'=>'visitor_privilege','label'=>'Visitor Privilege','rules'=>'trim',),
        array('field'=>'visitor_type','label'=>'Visitor Type','rules'=>'trim',),
        array('field'=>'visitor_status','label'=>'Visitor Status','rules'=>'trim',),
        array('field'=>'visitor_status_remarks','label'=>'Visitor Status Remarks','rules'=>'trim',),
        array('field'=>'buyerclass','label'=>'Buyer class','rules'=>'trim',),
        array('field'=>'buyerclass_remarks','label'=>'Buyer Class Remark','rules'=>'trim',),
        array('field'=>'valid_email','label'=>'Valid Email','rules'=>'trim',),
        array('field'=>'validated','label'=>'Validated','rules'=>'trim',),
        array('field'=>'date_validated','label'=>'Date validated','rules'=>'trim',),
        array('field'=>'validated_by','label'=>'Validated by','rules'=>'trim',),
        array('field'=>'emailed','label'=>'Emailed','rules'=>'trim',),
        array('field'=>'date_emailed','label'=>'Date emailed','rules'=>'trim',),
        array('field'=>'date_apply','label'=>'Date Apply','rules'=>'trim',),
        array('field'=>'date_input','label'=>'Date Input','rules'=>'trim',),
        array('field'=>'date_arrive','label'=>'Date Arrived','rules'=>'trim',),
        array('field'=>'url_form','label'=>'URL Form','rules'=>'trim',),
        array('field'=>'supplier_info','label'=>'Supplier Info','rules'=>'trim',),
        array('field'=>'app_system','label'=>'App System','rules'=>'trim',),
        array('field'=>'user_agreement','label'=>'User Agreement','rules'=>'trim',),
        array('field'=>'validation_status','label'=>'Validation Status','rules'=>'trim',),
        array('field'=>'subscription','label'=>'Subscription','rules'=>'trim',),

        array('field'=>'market_segment','label'=>'Market Segment','rules'=>'trim',),
        array('field'=>'annual_sales','label'=>'Annual Sales','rules'=>'trim',),
        array('field'=>'job_function','label'=>'Company Role','rules'=>'trim',),
        array('field'=>'representation','label'=>'Nature of Business','rules'=>'trim',),
        // array('field'=>'prod_category','label'=>'Quick Email Status','rules'=>'trim',),
        array('field'=>'prod_sub_category','label'=>'Minor Product','rules'=>'trim',),
        array('field'=>'technique','label'=>'Product Interest','rules'=>'trim',),
        array('field'=>'show_reason','label'=>'Reasons','rules'=>'trim',),
        array('field'=>'informthru','label'=>'Learn About','rules'=>'trim',),
        array('field'=>'product_interest','label'=>'Product Interest','rules'=>'trim',),
        array('field'=>'products_services','label'=>'Product Services','rules'=>'trim',),
        array('field'=>'reference_id','label'=>'Reference ID','rules'=>'trim',),
    ),
    'buyers_patch' =>array(
        array('field'=>'barcode','label'=>'Barcode','rules'=>'trim',),
        array('field'=>'co_name','label'=>'Company Name','rules'=>'trim',),
        array('field'=>'description','label'=>'Description','rules'=>'trim',),
        array('field'=>'cont_per_fn','label'=>'Contact First Name','rules'=>'trim|max_length[50]',),
        array('field'=>'cont_per_ln','label'=>'Contact Last Name','rules'=>'trim|max_length[50]',),
        array('field'=>'mi','label'=>'Middle Initial','rules'=>'trim',),
        array('field'=>'title','label'=>'Title','rules'=>'trim',),     
        array('field'=>'salutation','label'=>'Salutation','rules'=>'trim',),
        array('field'=>'gender','label'=>'Gender','rules'=>'trim|max_length[50]',),
        array('field'=>'age_group','label'=>'Age Group','rules'=>'trim',),
        array('field'=>'birthdate','label'=>'Date of Birth','rules'=>'trim',),
        array('field'=>'nationality','label'=>'Nationality','rules'=>'trim',),
        array('field'=>'accompanying_person','label'=>'Accompanying person','rules'=>'trim',),
        array('field'=>'country','label'=>'Country','rules'=>'trim',),
        array('field'=>'continent','label'=>'Continent','rules'=>'trim',),
        array('field'=>'states','label'=>'States','rules'=>'trim',),
        array('field'=>'region','label'=>'Region','rules'=>'trim',),
        array('field'=>'area','label'=>'Area','rules'=>'trim|max_length[32]',),
        array('field'=>'province','label'=>'Province','rules'=>'trim',),
        array('field'=>'add_st','label'=>'Street Address','rules'=>'trim|max_length[50]',),
        array('field'=>'add_city','label'=>'City Address','rules'=>'trim|max_length[50]',),
        array('field'=>'zipcode','label'=>'Zipcode','rules'=>'trim|max_length[5]',),
        array('field'=>'tel_off','label'=>'Office telephone','rules'=>'trim',),
        array('field'=>'tel_show','label'=>'Showroom Telephone','rules'=>'trim',),
        array('field'=>'fax','label'=>'Fax number','rules'=>'trim',),
        // array('field'=>'email','label'=>'Email','rules'=>'trim',),
        array('field'=>'email2','label'=>'Second email','rules'=>'trim',),
        array('field'=>'work_email','label'=>'Work email','rules'=>'trim',),
        array('field'=>'webpage','label'=>'Webpage','rules'=>'trim',),
        array('field'=>'first_time_asia','label'=>'First time asia','rules'=>'trim',),
        array('field'=>'attend_mfi','label'=>'Attend MFI','rules'=>'trim',),
        array('field'=>'pref_day','label'=>'Pref Day','rules'=>'trim',),
        array('field'=>'venue','label'=>'Venue','rules'=>'trim',),
        array('field'=>'deleted','label'=>'Deleted','rules'=>'trim',),
        array('field'=>'mobile','label'=>'Mobile','rules'=>'trim',),
        array('field'=>'exhi_conf_gov','label'=>'exhi_conf_gov','rules'=>'trim',),
        array('field'=>'added','label'=>'Added','rules'=>'trim',),
        array('field'=>'added_value','label'=>'Added Value','rules'=>'trim',),
        array('field'=>'added_count','label'=>'Added Count','rules'=>'trim',),
        array('field'=>'unsubscribe','label'=>'Unsubscribe','rules'=>'trim',),
        array('field'=>'marked','label'=>'marked','rules'=>'trim',),
        array('field'=>'tag','label'=>'Tag','rules'=>'trim',),
        array('field'=>'gcclaimed','label'=>'GC Claimed','rules'=>'trim',),
        array('field'=>'gcdate','label'=>'GC Date','rules'=>'trim',),
        array('field'=>'pid','label'=>'PID','rules'=>'trim',),
        array('field'=>'cutoff','label'=>'Cutoff','rules'=>'trim',),
        // array('field'=>'remarks','label'=>'remarks','rules'=>'trim',),
        array('field'=>'specific_request','label'=>'Specific request','rules'=>'trim',),
        array('field'=>'number_retail_stores','label'=>'Number of retail Store','rules'=>'trim',),
        array('field'=>'list_of_clients','label'=>'List of Clients','rules'=>'trim',),
        array('field'=>'facebook','label'=>'Facebook','rules'=>'trim',),
        array('field'=>'linkedin','label'=>'Linkedin','rules'=>'trim',),
        array('field'=>'blogsite','label'=>'Blog Site','rules'=>'trim',),
        array('field'=>'twitter','label'=>'Twitter','rules'=>'trim',),
        array('field'=>'instagram','label'=>'Instagram','rules'=>'trim',),
        array('field'=>'pinterest','label'=>'Pinterest','rules'=>'trim',),
        array('field'=>'weibo','label'=>'Weibo','rules'=>'trim',),
        array('field'=>'social_others','label'=>'Other Social Media Accounts','rules'=>'trim',),
        array('field'=>'y_estab','label'=>'Year Established','rules'=>'trim',),
        array('field'=>'rfid','label'=>'RFID','rules'=>'trim',),
        array('field'=>'org_name','label'=>'Organization Name','rules'=>'trim',),
        array('field'=>'org_website','label'=>'Organization Website','rules'=>'trim',),
        // array('field'=>'fameplus_id','label'=>'FAME+ ID','rules'=>'trim',),
        array('field'=>'password','label'=>'Password','rules'=>'trim',),

        array('field'=>'fair_code','label'=>'Fair Code','rules'=>'trim',),
        array('field'=>'sector','label'=>'Sector','rules'=>'trim',),
        array('field'=>'remarks','label'=>'Remarks','rules'=>'trim',),
        array('field'=>'pre_reg','label'=>'Pre Reg','rules'=>'trim',),
        array('field'=>'visitor_privilege','label'=>'Visitor Privilege','rules'=>'trim',),
        array('field'=>'visitor_type','label'=>'Visitor Type','rules'=>'trim',),
        array('field'=>'visitor_status','label'=>'Visitor Status','rules'=>'trim',),
        array('field'=>'visitor_status_remarks','label'=>'Visitor Status Remarks','rules'=>'trim',),
        array('field'=>'buyerclass','label'=>'Buyer class','rules'=>'trim',),
        array('field'=>'buyerclass_remarks','label'=>'Buyer Class Remark','rules'=>'trim',),
        array('field'=>'valid_email','label'=>'Valid Email','rules'=>'trim',),
        array('field'=>'validated','label'=>'Validated','rules'=>'trim',),
        array('field'=>'date_validated','label'=>'Date validated','rules'=>'trim',),
        array('field'=>'validated_by','label'=>'Validated by','rules'=>'trim',),
        array('field'=>'emailed','label'=>'Emailed','rules'=>'trim',),
        array('field'=>'date_emailed','label'=>'Date emailed','rules'=>'trim',),
        array('field'=>'date_apply','label'=>'Date Apply','rules'=>'trim',),
        array('field'=>'date_input','label'=>'Date Input','rules'=>'trim',),
        array('field'=>'date_arrive','label'=>'Date Arrived','rules'=>'trim',),
        array('field'=>'url_form','label'=>'URL Form','rules'=>'trim',),
        array('field'=>'supplier_info','label'=>'Supplier Info','rules'=>'trim',),
        array('field'=>'app_system','label'=>'App System','rules'=>'trim',),
        array('field'=>'user_agreement','label'=>'User Agreement','rules'=>'trim',),
        array('field'=>'validation_status','label'=>'Validation Status','rules'=>'trim',),
        array('field'=>'subscription','label'=>'Subscription','rules'=>'trim',),

        array('field'=>'market_segment','label'=>'Market Segment','rules'=>'trim',),
        array('field'=>'annual_sales','label'=>'Annual Sales','rules'=>'trim',),
        array('field'=>'job_function','label'=>'Company Role','rules'=>'trim',),
        array('field'=>'representation','label'=>'Nature of Business','rules'=>'trim',),
        // array('field'=>'prod_category','label'=>'Quick Email Status','rules'=>'trim',),
        array('field'=>'prod_sub_category','label'=>'Minor Product','rules'=>'trim',),
        array('field'=>'technique','label'=>'Product Interest','rules'=>'trim',),
        array('field'=>'show_reason','label'=>'Reasons','rules'=>'trim',),
        array('field'=>'informthru','label'=>'Learn About','rules'=>'trim',),
        array('field'=>'product_interest','label'=>'Product Interest','rules'=>'trim',),
        array('field'=>'products_services','label'=>'Product Services','rules'=>'trim',),
        array('field'=>'reference_id','label'=>'Reference ID','rules'=>'trim',),
    ),
    'buyers_put' =>array(
        array('field'=>'co_email','label'=>'Email_address','rules'=>'trim|valid_email',),
        array('field'=>'password','label'=>'Password','rules'=>'trim|min_length[8]|max_length[16]',),
        array('field'=>'cont_per_fn','label'=>'First Name','rules'=>'trim|max_length[50]',),
        array('field'=>'cont_per_ln','label'=>'Last Name','rules'=>'trim|max_length[50]',),
    ),
    'fameplus_id_patch'=>array(
        array('field'=>'fameplus_id','label'=>'Fame+ Id','rules'=>'trim|required',),
    ),
    'validate_buyer_patch'=>array(
        array('field'=>'validation_status','label'=>'Validation status','rules'=>'trim|required',),
    ),
    'account_email_patch'=>array(
        array('field'=>'new_email','label'=>'New Email','rules'=>'trim|required|valid_email',),
    ),
    'exhibitors_post'=>array(
        array('field'=>'ff_code','label'=>'Exhibitor ID','rules'=>'trim',),
        array('field'=>'co_name','label'=>'Company Name','rules'=>'trim',),
        array('field'=>'brand_name','label'=>'Brand Name','rules'=>'trim',),
        array('field'=>'description','label'=>'Description','rules'=>'trim',),
        array('field'=>'registration_no','label'=>'Registration No.','rules'=>'trim',),
        array('field'=>'y_estab','label'=>'Year Established','rules'=>'trim',),
        array('field'=>'y_export','label'=>'Year Exported','rules'=>'trim',),
        array('field'=>'cont_per_fn','label'=>'First Name','rules'=>'trim',),
        array('field'=>'cont_per_ln','label'=>'Last Name','rules'=>'trim',),
        array('field'=>'mi','label'=>'Middle Intial','rules'=>'trim',),
        array('field'=>'title','label'=>'Title /  Designation','rules'=>'trim',),
        array('field'=>'salutation','label'=>'Salutation','rules'=>'trim',),
        array('field'=>'gender','label'=>'Gender','rules'=>'trim',),
        array('field'=>'age_group','label'=>'Age Group','rules'=>'trim',),
        array('field'=>'date_apply','label'=>'Date Created','rules'=>'trim',),
        array('field'=>'date_input','label'=>'Date Modified','rules'=>'trim',),
        array('field'=>'country','label'=>'Country','rules'=>'trim',),
        array('field'=>'continent','label'=>'Continent','rules'=>'trim',),
        array('field'=>'states','label'=>'States','rules'=>'trim',),
        array('field'=>'region','label'=>'Region','rules'=>'trim',),
        array('field'=>'area','label'=>'Area','rules'=>'trim',),
        array('field'=>'province','label'=>'Province','rules'=>'trim',),
        array('field'=>'add_st','label'=>'Street Address','rules'=>'trim',),
        array('field'=>'add_city','label'=>'City Address','rules'=>'trim',),
        array('field'=>'zipcode','label'=>'Zipcode','rules'=>'trim',),
        array('field'=>'tel_off','label'=>'Office Telephone','rules'=>'trim',),
        array('field'=>'fax','label'=>'Fax Number','rules'=>'trim',),
        array('field'=>'co_mobile','label'=>'Company Mobile Number','rules'=>'trim',),
        array('field'=>'owner_mobile','label'=>'Owner Mobile Number','rules'=>'trim',),
        array('field'=>'owner_email','label'=>'Owner Email Address','rules'=>'trim',),
        array('field'=>'co_email','label'=>'Company Email','rules'=>'trim|required|valid_email',),
        array('field'=>'webpage','label'=>'Webpage','rules'=>'trim',),
        array('field'=>'remarks','label'=>'Remarks','rules'=>'trim',),
        array('field'=>'remarks_date','label'=>'Remarks Date','rules'=>'trim',),
        array('field'=>'deleted','label'=>'Deleted','rules'=>'trim',),
        array('field'=>'remarks1','label'=>'Remarks 1','rules'=>'trim',),
        // array('field'=>'edited','label'=>'Edited','rules'=>'trim',),
        array('field'=>'fair_code','label'=>'Fair Code','rules'=>'trim',),
        array('field'=>'stand_name','label'=>'Stand Name','rules'=>'trim',),
        array('field'=>'tin','label'=>'TIN','rules'=>'trim',),
        array('field'=>'facebook','label'=>'Facebook','rules'=>'trim',),
        array('field'=>'twitter','label'=>'Twitted','rules'=>'trim',),
        array('field'=>'instagram','label'=>'Instagram','rules'=>'trim',),
        array('field'=>'youtube','label'=>'Youtube','rules'=>'trim',),
        array('field'=>'linkedin','label'=>'Linkedin','rules'=>'trim',),
        array('field'=>'tiktok','label'=>'Tiktok','rules'=>'trim',),
        array('field'=>'behance','label'=>'Behance','rules'=>'trim',),
        array('field'=>'portfolio','label'=>'Portfolio','rules'=>'trim',),
        array('field'=>'username','label'=>'Username','rules'=>'trim',),
        array('field'=>'userdesc','label'=>'User Description','rules'=>'trim',),
        array('field'=>'logo','label'=>'Logo','rules'=>'trim',),
        array('field'=>'membership_assoc','label'=>'Membership Association','rules'=>'trim',),
        array('field'=>'password','label'=>'Password','rules'=>'trim',),
        array('field'=>'rights','label'=>'Rights','rules'=>'trim',),
        array('field'=>'forgotten_password_code','label'=>'Forgotten Password Code','rules'=>'trim',),
        array('field'=>'forgotten_password_time','label'=>'Forgotten Password Time','rules'=>'trim',),
        array('field'=>'last_login','label'=>'Last Login','rules'=>'trim',),
        array('field'=>'active','label'=>'Active','rules'=>'trim',),
        array('field'=>'slug','label'=>'Slug','rules'=>'trim',),
        array('field'=>'image','label'=>'Image','rules'=>'trim',),
        array('field'=>'youtube_id','label'=>'YouTube ID','rules'=>'trim',),
        array('field'=>'sector','label'=>'Sector Code','rules'=>'trim',),
        array('field'=>'details','label'=>'Details','rules'=>'trim',),
        array('field'=>'social_others','label'=>'Other Social Media','rules'=>'trim',),
        array('field'=>'level','label'=>'Level','rules'=>'trim',),
        array('field'=>'foldername','label'=>'Folder Name','rules'=>'trim',),
        array('field'=>'messaging_app','label'=>'Messaging App','rules'=>'trim',),
        array('field'=>'fameplus_id','label'=>'FAME+ Id','rules'=>'trim',),
        array('field'=>'dtcp_id','label'=>'ID','rules'=>'trim',),

        array('field'=>'proj','label'=>'Project Name','rules'=>'trim',),
        array('field'=>'fair_code','label'=>'Fair Code','rules'=>'trim',),
        array('field'=>'fair_stat_app','label'=>'Fair Stat App','rules'=>'trim',),
        array('field'=>'fair_stat_app_date','label'=>'Fair Stat App Date','rules'=>'trim',),
        array('field'=>'fair_stat_part','label'=>'Fair Status Participation ','rules'=>'trim',),
        array('field'=>'foreignlocal','label'=>'ForeignLocal','rules'=>'trim',),
        array('field'=>'foreignlocalremarks','label'=>'ForeignLocal','rules'=>'trim',),
        array('field'=>'coordinator','label'=>'Coordinator','rules'=>'trim',),
        array('field'=>'sector_code','label'=>'sector_code','rules'=>'trim',),
        array('field'=>'participation_type','label'=>'Participation Type','rules'=>'trim',),
        array('field'=>'direct_workers','label'=>'Number of Direct Workers','rules'=>'trim',),
        array('field'=>'indirect_workers','label'=>'Number of Indirect Workers','rules'=>'trim',),
        array('field'=>'company_size','label'=>'Company Size','rules'=>'trim',),
        array('field'=>'business_ownership','label'=>'Business ownership','rules'=>'trim',),
        array('field'=>'user_agreement','label'=>'User Agreement','rules'=>'trim',),
        array('field'=>'exhibit_participation','label'=>'Exhibit Participation','rules'=>'trim',),
       
        array('field'=>'industry_affiliation','label'=>'Industry Affiliation','rules'=>'trim',),
        array('field'=>'business_category','label'=>'Business Category','rules'=>'trim',),
        array('field'=>'target_buyers','label'=>'Target Buyers','rules'=>'trim',),
        array('field'=>'nature_of_business','label'=>'Nature of Business','rules'=>'trim',),
        array('field'=>'market_segment','label'=>'Market Segment','rules'=>'trim',),
        array('field'=>'trade_experience','label'=>'Name','Trade Experience'=>'trim',),
        array('field'=>'top_countries','label'=>'Top Countries','rules'=>'trim',),
        array('field'=>'export_market','label'=>'Top 3 Export Market','rules'=>'trim',),
        array('field'=>'target_countries','label'=>'Top Countries','rules'=>'trim',),
        array('field'=>'product_sub_category','label'=>'Product Sub Category','rules'=>'trim',),
        array('field'=>'annualsales','label'=>'Annual Sales','rules'=>'trim',),
        array('field'=>'certification','label'=>'Certifications','rules'=>'trim',),
        array('field'=>'digital_participation','label'=>'Digital participation','rules'=>'trim',),
        array('field'=>'physical_participation','label'=>'Physical participation','rules'=>'trim',),

        array('field'=>'name','label'=>'Name','rules'=>'trim',),
        array('field'=>'registered','label'=>'Philippine Registered','rules'=>'trim',),
        array('field'=>'participated','label'=>'Participated','rules'=>'trim',),
        array('field'=>'year_participated','label'=>'Year Participated','rules'=>'trim',), 
        array('field'=>'tel_off_countrycode','label'=>'Landline country code','rules'=>'trim',),
        array('field'=>'tel_off_areacode','label'=>'landline areacode','rules'=>'trim',),
        array('field'=>'tel_off_number','label'=>'landline number','rules'=>'trim',),
        array('field'=>'nature_of_participation','label'=>'Nature of Participation','rules'=>'trim',),

        array('field'=>'fact_st','label'=>'Factory Street Addess','rules'=>'trim',),
        array('field'=>'fact_city','label'=>'Factory City Addess','rules'=>'trim',),
        array('field'=>'fact_region','label'=>'Factory Region','rules'=>'trim',),
        array('field'=>'fact_country','label'=>'Factory Country','rules'=>'trim',),
        array('field'=>'fact_continent','label'=>'Factory Continent','rules'=>'trim',),
        array('field'=>'fact_zipcode','label'=>'Factory Zipcode','rules'=>'trim',),

        array('field'=>'rep_cont_per_fn','label'=>'Representative First Name','rules'=>'trim',),
        array('field'=>'rep_cont_per_ln','label'=>'Representative Last Name','rules'=>'trim',),
        array('field'=>'rep_mi','label'=>'Representative Middle Intial','rules'=>'trim',),
        array('field'=>'rep_title','label'=>'Representative Designation','rules'=>'trim',),
        array('field'=>'rep_mobile','label'=>'Representative mobile','rules'=>'trim',),
        array('field'=>'rep_messaging_app','label'=>'Representative messaging app','rules'=>'trim',),
        array('field'=>'rep_email','label'=>'Representative email','rules'=>'trim',),

        array('field'=>'sec_dti_doc','label'=>'sec_dti_doc','rules'=>'trim',),
        array('field'=>'permit_doc','label'=>'permit_doc','rules'=>'trim',),
        array('field'=>'license_cert_doc','label'=>'license_cert_doc','rules'=>'trim',),
        array('field'=>'export_declaration_doc','label'=>'export_declaration_doc','rules'=>'trim',),
        array('field'=>'training_cert_doc','label'=>'training_cert_doc','rules'=>'trim',),
        array('field'=>'endorse_letter_doc','label'=>'endorse_letter_doc','rules'=>'trim',),
        array('field'=>'portfolio_doc','label'=>'portfolio_doc','rules'=>'trim',),
        array('field'=>'gov_id_doc','label'=>'gov_id_doc','rules'=>'trim',),
        array('field'=>'reg_cert_doc','label'=>'reg_cert_doc','rules'=>'trim',),
        array('field'=>'business_permit_doc','label'=>'reg_cert_doc','rules'=>'trim',),

        array('field'=>'exhibitor_category','label'=>'Exhibitor Category','rules'=>'trim',),
        array('field'=>'reference_id','label'=>'Reference ID','rules'=>'trim|required',),
        array('field'=>'products_services','label'=>'Products and Services','rules'=>'trim',),
        array('field'=>'other_mobile','label'=>'other mobile','rules'=>'trim',),
        array('field'=>'other_emails','label'=>'other emails','rules'=>'trim',), 
        array('field'=>'other_webpage','label'=>'other webpage','rules'=>'trim',),
        array('field'=>'major_expertise','label'=>'Major Expertise','rules'=>'trim',),

    ),
    'exhibitors_patch'=>array(
        array('field'=>'ff_code','label'=>'Exhibitor ID','rules'=>'trim',),
        array('field'=>'co_name','label'=>'Company Name','rules'=>'trim',),
        array('field'=>'brand_name','label'=>'Brand Name','rules'=>'trim',),
        array('field'=>'description','label'=>'Description','rules'=>'trim',),
        array('field'=>'registration_no','label'=>'Registration No.','rules'=>'trim',),
        array('field'=>'y_estab','label'=>'Year Established','rules'=>'trim',),
        array('field'=>'y_export','label'=>'Year Exported','rules'=>'trim',),
        array('field'=>'cont_per_fn','label'=>'First Name','rules'=>'trim',),
        array('field'=>'cont_per_ln','label'=>'Last Name','rules'=>'trim',),
        array('field'=>'mi','label'=>'Middle Intial','rules'=>'trim',),
        array('field'=>'title','label'=>'Title /  Designation','rules'=>'trim',),
        array('field'=>'salutation','label'=>'Salutation','rules'=>'trim',),
        array('field'=>'gender','label'=>'Gender','rules'=>'trim',),
        array('field'=>'age_group','label'=>'Age Group','rules'=>'trim',),
        array('field'=>'date_apply','label'=>'Date Created','rules'=>'trim',),
        array('field'=>'date_input','label'=>'Date Modified','rules'=>'trim',),
        array('field'=>'country','label'=>'Country','rules'=>'trim',),
        array('field'=>'continent','label'=>'Continent','rules'=>'trim',),
        array('field'=>'states','label'=>'States','rules'=>'trim',),
        array('field'=>'region','label'=>'Region','rules'=>'trim',),
        array('field'=>'area','label'=>'Area','rules'=>'trim',),
        array('field'=>'province','label'=>'Province','rules'=>'trim',),
        array('field'=>'add_st','label'=>'Street Address','rules'=>'trim',),
        array('field'=>'add_city','label'=>'City Address','rules'=>'trim',),
        array('field'=>'zipcode','label'=>'Zipcode','rules'=>'trim',),
        array('field'=>'tel_off','label'=>'Office Telephone','rules'=>'trim',),
        array('field'=>'fax','label'=>'Fax Number','rules'=>'trim',),
        array('field'=>'co_mobile','label'=>'Company Mobile Number','rules'=>'trim',),
        array('field'=>'owner_mobile','label'=>'Owner Mobile Number','rules'=>'trim',),
        array('field'=>'owner_email','label'=>'Owner Email Address','rules'=>'trim',),
        // array('field'=>'co_email','label'=>'Company Email','rules'=>'trim|required|valid_email',),
        array('field'=>'webpage','label'=>'Webpage','rules'=>'trim',),
        array('field'=>'remarks','label'=>'Remarks','rules'=>'trim',),
        array('field'=>'remarks_date','label'=>'Remarks Date','rules'=>'trim',),
        array('field'=>'deleted','label'=>'Deleted','rules'=>'trim',),
        array('field'=>'remarks1','label'=>'Remarks 1','rules'=>'trim',),
        // array('field'=>'edited','label'=>'Edited','rules'=>'trim',),
        array('field'=>'fair_code','label'=>'Fair Code','rules'=>'trim',),
        array('field'=>'stand_name','label'=>'Stand Name','rules'=>'trim',),
        array('field'=>'tin','label'=>'TIN','rules'=>'trim',),
        array('field'=>'facebook','label'=>'Facebook','rules'=>'trim',),
        array('field'=>'twitter','label'=>'Twitted','rules'=>'trim',),
        array('field'=>'instagram','label'=>'Instagram','rules'=>'trim',),
        array('field'=>'portfolio','label'=>'Portfolio','rules'=>'trim',),
        array('field'=>'username','label'=>'Username','rules'=>'trim',),
        array('field'=>'userdesc','label'=>'User Description','rules'=>'trim',),
        array('field'=>'logo','label'=>'Logo','rules'=>'trim',),
        array('field'=>'membership_assoc','label'=>'Membership Association','rules'=>'trim',),
        array('field'=>'password','label'=>'Password','rules'=>'trim',),
        array('field'=>'rights','label'=>'Rights','rules'=>'trim',),
        array('field'=>'forgotten_password_code','label'=>'Forgotten Password Code','rules'=>'trim',),
        array('field'=>'forgotten_password_time','label'=>'Forgotten Password Time','rules'=>'trim',),
        array('field'=>'last_login','label'=>'Last Login','rules'=>'trim',),
        array('field'=>'active','label'=>'Active','rules'=>'trim',),
        array('field'=>'slug','label'=>'Slug','rules'=>'trim',),
        array('field'=>'image','label'=>'Image','rules'=>'trim',),
        array('field'=>'youtube_id','label'=>'YouTube ID','rules'=>'trim',),
        array('field'=>'sector','label'=>'Sector Code','rules'=>'trim',),
        array('field'=>'details','label'=>'Details','rules'=>'trim',),
        array('field'=>'linkedin','label'=>'Linkedin','rules'=>'trim',),
        array('field'=>'social_others','label'=>'Other Social Media','rules'=>'trim',),
        array('field'=>'level','label'=>'Level','rules'=>'trim',),
        array('field'=>'foldername','label'=>'Folder Name','rules'=>'trim',),
        array('field'=>'messaging_app','label'=>'Messaging App','rules'=>'trim',),
        array('field'=>'fameplus_id','label'=>'FAME+ Id','rules'=>'trim',),
        array('field'=>'dtcp_id','label'=>'ID','rules'=>'trim',),

        array('field'=>'proj','label'=>'Project Name','rules'=>'trim',),
        array('field'=>'fair_code','label'=>'Fair Code','rules'=>'trim',),
        array('field'=>'fair_stat_app','label'=>'Fair Stat App','rules'=>'trim',),
        array('field'=>'fair_stat_app_date','label'=>'Fair Stat App Date','rules'=>'trim',),
        array('field'=>'fair_stat_part','label'=>'Fair Status Participation ','rules'=>'trim',),
        array('field'=>'foreignlocal','label'=>'ForeignLocal','rules'=>'trim',),
        array('field'=>'foreignlocalremarks','label'=>'ForeignLocal','rules'=>'trim',),
        array('field'=>'coordinator','label'=>'Coordinator','rules'=>'trim',),
        array('field'=>'sector_code','label'=>'sector_code','rules'=>'trim',),
        array('field'=>'participation_type','label'=>'Participation Type','rules'=>'trim',),
        array('field'=>'direct_workers','label'=>'Number of Direct Workers','rules'=>'trim',),
        array('field'=>'indirect_workers','label'=>'Number of Indirect Workers','rules'=>'trim',),
        array('field'=>'company_size','label'=>'Company Size','rules'=>'trim',),
        array('field'=>'business_ownership','label'=>'Business ownership','rules'=>'trim',),
        array('field'=>'user_agreement','label'=>'User Agreement','rules'=>'trim',),
        array('field'=>'exhibit_participation','label'=>'Exhibit Participation','rules'=>'trim',),
       
        array('field'=>'industry_affiliation','label'=>'Industry Affiliation','rules'=>'trim',),
        array('field'=>'business_category','label'=>'Business Category','rules'=>'trim',),
        array('field'=>'target_buyers','label'=>'Target Buyers','rules'=>'trim',),
        array('field'=>'nature_of_business','label'=>'Nature of Business','rules'=>'trim',),
        array('field'=>'market_segment','label'=>'Market Segment','rules'=>'trim',),
        array('field'=>'trade_experience','label'=>'Name','Trade Experience'=>'trim',),
        array('field'=>'top_countries','label'=>'Top Countries','rules'=>'trim',),
        array('field'=>'export_market','label'=>'Top 3 Export Market','rules'=>'trim',),
        array('field'=>'target_countries','label'=>'Top Countries','rules'=>'trim',),
        array('field'=>'product_sub_category','label'=>'Product Sub Category','rules'=>'trim',),
        array('field'=>'annualsales','label'=>'Annual Sales','rules'=>'trim',),
        array('field'=>'certification','label'=>'Certifications','rules'=>'trim',),
        array('field'=>'digital_participation','label'=>'Digital participation','rules'=>'trim',),
        array('field'=>'physical_participation','label'=>'Physical participation','rules'=>'trim',),

        array('field'=>'name','label'=>'Name','rules'=>'trim',),
        array('field'=>'registered','label'=>'Philippine Registered','rules'=>'trim',),
        array('field'=>'participated','label'=>'Participated','rules'=>'trim',),
        array('field'=>'year_participated','label'=>'Year Participated','rules'=>'trim',), 
        array('field'=>'tel_off_countrycode','label'=>'Landline country code','rules'=>'trim',),
        array('field'=>'tel_off_areacode','label'=>'landline areacode','rules'=>'trim',),
        array('field'=>'tel_off_number','label'=>'landline number','rules'=>'trim',),
        array('field'=>'nature_of_participation','label'=>'Nature of Participation','rules'=>'trim',),

        array('field'=>'fact_st','label'=>'Factory Street Addess','rules'=>'trim',),
        array('field'=>'fact_city','label'=>'Factory City Addess','rules'=>'trim',),
        array('field'=>'fact_region','label'=>'Factory Region','rules'=>'trim',),
        array('field'=>'fact_country','label'=>'Factory Country','rules'=>'trim',),
        array('field'=>'fact_continent','label'=>'Factory Continent','rules'=>'trim',),
        array('field'=>'fact_zipcode','label'=>'Factory Zipcode','rules'=>'trim',),

        array('field'=>'rep_cont_per_fn','label'=>'Representative First Name','rules'=>'trim',),
        array('field'=>'rep_cont_per_ln','label'=>'Representative Last Name','rules'=>'trim',),
        array('field'=>'rep_mi','label'=>'Representative Middle Intial','rules'=>'trim',),
        array('field'=>'rep_title','label'=>'Representative Designation','rules'=>'trim',),
        array('field'=>'rep_mobile','label'=>'Representative mobile','rules'=>'trim',),
        array('field'=>'rep_messaging_app','label'=>'Representative messaging app','rules'=>'trim',),
        array('field'=>'rep_email','label'=>'Representative email','rules'=>'trim',),

        array('field'=>'sec_dti_doc','label'=>'sec_dti_doc','rules'=>'trim',),
        array('field'=>'permit_doc','label'=>'permit_doc','rules'=>'trim',),
        array('field'=>'license_cert_doc','label'=>'license_cert_doc','rules'=>'trim',),
        array('field'=>'export_declaration_doc','label'=>'export_declaration_doc','rules'=>'trim',),
        array('field'=>'training_cert_doc','label'=>'training_cert_doc','rules'=>'trim',),
        array('field'=>'endorse_letter_doc','label'=>'endorse_letter_doc','rules'=>'trim',),
        array('field'=>'portfolio_doc','label'=>'portfolio_doc','rules'=>'trim',),
        array('field'=>'gov_id_doc','label'=>'gov_id_doc','rules'=>'trim',),
        array('field'=>'reg_cert_doc','label'=>'reg_cert_doc','rules'=>'trim',),
        array('field'=>'business_permit_doc','label'=>'reg_cert_doc','rules'=>'trim',),

        array('field'=>'exhibitor_category','label'=>'Exhibitor Category','rules'=>'trim',),
        array('field'=>'reference_id','label'=>'Reference ID','rules'=>'trim',),
        array('field'=>'products_services','label'=>'Products and Services','rules'=>'trim',),
        array('field'=>'other_emails','label'=>'other emails','rules'=>'trim',),
        array('field'=>'other_mobile','label'=>'other mobile','rules'=>'trim',),
        array('field'=>'other_webpage','label'=>'other webpage','rules'=>'trim',),
        array('field'=>'major_expertise','label'=>'Major Expertise','rules'=>'trim',),

        
        
    ),
    'validate_exhibitor_patch'=>array(
        array('field'=>'validation_status','label'=>'Validation status','rules'=>'trim|required',),
        array('field'=>'deleted','label'=>'Deleted','rules'=>'trim',),
        array('field'=>'fair_code','label'=>'Fair code','rules'=>'trim',),
    ),

    'subscriptions_post' =>array(
        array('field'=>'country','label'=>'Country','rules'=>'trim',),
        array('field'=>'email','label'=>'Email','rules'=>'trim|required|valid_email',),
        array('field'=>'visitor_type','label'=>'Visitor Type','rules'=>'trim',),
        array('field'=>'user_agreement','label'=>'User Agreement','rules'=>'trim|required',),
        array('field'=>'interest','label'=>'Interest','rules'=>'trim',),
        array('field'=>'representation','label'=>'Representation','rules'=>'trim',),
    ),
    'subscriptions_patch' =>array(
        array('field'=>'country','label'=>'Country','rules'=>'trim',),
        array('field'=>'visitor_type','label'=>'Visitor Type','rules'=>'trim',),
        array('field'=>'user_agreement','label'=>'User Agreement','rules'=>'trim',),
        array('field'=>'interest','label'=>'Interest','rules'=>'trim',),
        array('field'=>'representation','label'=>'Representation','rules'=>'trim',),
    ),





);

?>